# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2736ff71449a95906810ce79656133e03748d23f690f27620ef6a03131a33e621c05db7390338a1db22d8e969ccb10ab50a74afc25b2ed9da9e752f306ff640e
  stripe_publishable_key: <%= ENV['STRIPE_TEST_PK_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_TEST_SK_KEY'] %>

test:
  secret_key_base: d7f0a65d6d3f4aeb41ed9e8805334a52b28efde793a927d3a0b1b17b5c746bac087bf3c748013d65c2ab58c69318ffb6fecbb51b3e45e8403b32b4717dffd32f
  stripe_publishable_key: <%= ENV['STRIPE_TEST_PK_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_TEST_SK_KEY'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLIC_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
